name: Test Script Validation

on:
  push:
    branches: 
      - main
      - roadmap/bash-jjarque
      - feature/github-actions
  pull_request:
    branches: 
     - main
     - roadmap/bash-jjarque
     - feature/github-actions
      
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v5
      
      - name: Dar permisos de ejecución
        run: |
          chmod +x scripts/01_basics/05_args_check.sh
          chmod +x scripts/01_basics/test-scripts/test05.sh
      
      - name: Ejecutar tests
        run: bash test05.sh
        working-directory: ./scripts/01_basics/test-scripts
      
      - name: Verificar resultados
        run: |
          if [ $? -eq 0 ]; then
            echo "Tests completados"
          else
            echo "Tests fallidos"
            exit 1
          fi
