name: bash-tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Marcar .sh como ejecutables
        run: |
          find scripts -type f -name '*.sh' -print0 | xargs -0 chmod +x

      - name: Ejecutar todos los test_*.sh
        run: |
          find scripts/tests -type f -name 'test_*.sh' | while read -r test_script; do
            if ! bash "$test_script" &> "${test_script%.sh}.log"; then
              echo "$test_script FAILED. Log:"
              cat "${test_script%.sh}.log
            else
              echo "$test_script OK"
            fi
          done